# Generated by Django 4.1.2 on 2023-01-10 20:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deliverer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deliverer_name", models.CharField(max_length=510)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_location", models.CharField(max_length=120)),
            ],
            options={
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clearance_debt", models.IntegerField(blank=True, null=True)),
                ("recovery_debt", models.IntegerField(blank=True, null=True)),
                ("agency_debt", models.IntegerField(blank=True, null=True)),
                (
                    "requirements_and_neccessities",
                    models.IntegerField(blank=True, null=True),
                ),
                ("auxillaries", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reciever",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=120)),
                ("location", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="Sender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=40)),
                ("full_name", models.CharField(max_length=40)),
                ("phone_number", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.CharField(blank=True, max_length=120, null=True)),
                ("quantity", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "mode_of_shipment",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "shipment_pick_up_date",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "shipment_type",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("comment", models.CharField(blank=True, max_length=120, null=True)),
                ("uuid", models.TextField(blank=True, null=True, unique=True)),
                (
                    "destination",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("is_arrived", models.BooleanField(default=False)),
                (
                    "deliverer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shipments.deliverer",
                    ),
                ),
                ("location", models.ManyToManyField(to="shipments.location")),
                (
                    "payments",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shipments.payment",
                    ),
                ),
                (
                    "reciever",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shipments.reciever",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shipments.sender",
                    ),
                ),
            ],
        ),
    ]
