# Generated by Django 4.1.2 on 2023-01-14 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="location",
        ),
        migrations.AddField(
            model_name="shipment",
            name="location",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="shipments.location",
            ),
            preserve_default=False,
        ),
    ]
