# Generated by Django 4.1.2 on 2023-01-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0002_remove_shipment_location_shipment_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="registered_by",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
